project:
  type: website
  output-dir: docs
  resources: 
    - files/CV-Crawford.pdf

editor: visual
brand: _brand.yml
highlight-style: breeze
title-block-style: none

# filters:
#   - auto-dark

format:
  html:
    smooth-scroll: true
    #page-layout: full
    grid:
      # sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 2rem
    code-copy: hover
    theme: 
      light: [flatly, brand, simplified-scss.scss] 
      # dark: [Flatly, brand] #, simplified-scss.scss] 
    # respect-user-color-scheme: true
    toc: true
    toc-location: left
    self-contained: false
    #fontsize: 1.1rem
    reference-location: margin
    include-in-header:
      text: |
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Jacquard+24&family=UnifrakturMaguntia&display=swap');
        </style>

website:
  title: "Patrick Crawford"
  favicon: images/favicon.png #favicon.ico
  twitter-card: true
  open-graph: true
  site-url: https://patrickjcrawford.github.io/
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - icon: twitter #bluesky
        href: https://bsky.app/profile/pjcrawford.bsky.social
      - icon: twitter-x
        href: https://twitter.com/_pcrawford
      - icon: github
        href: https://github.com/patrickjcrawford
      - icon: envelope-at
        href: mailto:pcrawfo6@gmu.edu
    right:
      - text: "CV"
        file: cv.qmd #"files/CV - Crawford.pdf"
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
  # sidebar:
  #   fontsize: 2rem
  #   style: "floating"
  #   # background: secondary
  #   contents:
  #     - text: "Research"
  #       href: research.qmd
  #     - text: "Teaching"
  #       href: teaching.qmd
  #     - text: "CV"
  #       file: "files/CV - Crawford.pdf"
  page-footer: |
    {{< now year >}} © Patrick Crawford
  