---
title: "PATRICK J. CRAWFORD"
subtitle: "[patrickjcrawford.github.io](https://patrickjcrawford.github.io) $\\diamond$ [pcrawfo6@gmu.edu](mailto:pcrawfo6@gmu.edu)"

format: 
    pdf:
      documentclass: article
      output-file: "CV-Crawford.pdf"
      papersize: letter
      margin-top: 0.75in
      margin-bottom: 1in
      margin-left: 0.75in
      margin-right: 0.75in
      fontfamily: libertine
      urlcolor: ForestGreen
      classoptions:
        - '`xcolor={x11names}`{=latex}'
      include-in-header: 
        text: |
          \usepackage{titlesec}
          \usepackage{titling}
          \setlength{\droptitle}{-1.5cm} 
          \pretitle{\begin{center}\Huge\bfseries}
          
          \titleformat{\section}[hang]{\normalfont\Large\bfseries}{\thesection}{1em}{}
          \titlespacing*{\section}{0pt}{15pt plus 2pt minus 2pt}{6pt plus 1pt minus 1pt}

          \titleformat{\subsection}[hang]{\normalfont\large\bfseries}{\thesubsection}{1em}{}
          \titlespacing*{\subsection}{0pt}{10pt plus 2pt minus 1pt}{4pt plus 1pt minus 1pt}
---

\vspace{-1.5cm}

# EDUCATION

## George Mason University

Ph.D., Economics \hfill exp. 2026

M.A., Economics \hfill 2021

B.A., Economics \hfill 2019

# EXPERIENCE

## Graduate Lecturer \hfill Fall 2021---Summer 2024

George Mason University \hfill Fairfax, VA

-   Principles of Macroeconomics
-   Intermediate Microeconomics
-   Economics of Developming Areas
-   International Economic Policy

## Research Assistant \hfill March 2022---May 2024

Dr. Mark Koyama, Department of Economics \hfill Fairfax, VA

# RESEARCH

## Working Papers

Late Medieval Unrest in the Holy Roman Empire: Causes and Consequences \hfill Drafting

Did Newspaper Competition Promote Rebellion? The Case of the 1837-38 Rebellions in Lower Canada \hfill Drafting

\vspace{-0.6em} *(with Vincent Geloso)*

The Specter of Slavery: Newspapers During the American Civil War \hfill Drafting

## In Progress

The Effects of Bureaucracy on Pandemic Outcomes

*Reichshofrat oder Reichskammergericht?* Court competition in the Early Modern Empire

Political Autonomy and Long-Run Urban Growth in Germany

## Research Interests

-   Economic History
-   Political Economy of Conflict and Violence
-   Growth and Development
-   Text Analysis

<!-- # CONFERENCES

Southern Economic Association Annual Meeting \hfill November 2022

Southern Economic Association Annual Meeting \hfill November 2023

Southern Economic Association Annual Meeting \hfill November 2024 -->

# SKILLS

## Languages

R (Web Scraping, GIS), Python (Text Analysis), QGIS, \LaTeX
